// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7tD7BzsHsNPk3OUbPs70jXI2izML3rmg',
    appId: '1:776092207100:web:f5e0be67eeb8a99a915479',
    messagingSenderId: '776092207100',
    projectId: 'blockchain-storage-app',
    authDomain: 'blockchain-storage-app.firebaseapp.com',
    storageBucket: 'blockchain-storage-app.appspot.com',
    measurementId: 'G-YN10ZTR6PP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFlc6_hg-_se9VZ6pwnMMpuhBEdbGEiTU',
    appId: '1:776092207100:android:4695afcdbebf4ccd915479',
    messagingSenderId: '776092207100',
    projectId: 'blockchain-storage-app',
    storageBucket: 'blockchain-storage-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBViC0Y8wxF9pe-q0_y2aS3FFCX4-yzW3I',
    appId: '1:776092207100:ios:a110f389fa43f7d0915479',
    messagingSenderId: '776092207100',
    projectId: 'blockchain-storage-app',
    storageBucket: 'blockchain-storage-app.appspot.com',
    iosClientId: '776092207100-jsv9fcqcemtdbmkgjaje8q49vs187gaa.apps.googleusercontent.com',
    iosBundleId: 'com.example.blockchainDecentralizedStorageSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBViC0Y8wxF9pe-q0_y2aS3FFCX4-yzW3I',
    appId: '1:776092207100:ios:a110f389fa43f7d0915479',
    messagingSenderId: '776092207100',
    projectId: 'blockchain-storage-app',
    storageBucket: 'blockchain-storage-app.appspot.com',
    iosClientId: '776092207100-jsv9fcqcemtdbmkgjaje8q49vs187gaa.apps.googleusercontent.com',
    iosBundleId: 'com.example.blockchainDecentralizedStorageSystem',
  );
}
